/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_req {
	int a;
	int b;
};
typedef struct sum_req sum_req;

#define SUM_PROG 0x31234567
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_SUM 1
extern  int * get_sum_1(sum_req *, CLIENT *);
extern  int * get_sum_1_svc(sum_req *, struct svc_req *);
extern int sum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_SUM 1
extern  int * get_sum_1();
extern  int * get_sum_1_svc();
extern int sum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_req (XDR *, sum_req*);

#else /* K&R C */
extern bool_t xdr_sum_req ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
